### ISSUE TITLE
lrnsys-button

### ISSUE THREAD

**Issue by rickhumphries** [buttercupstraining/lrnwebcomponents#2]
UPDATE: Below is identification of what needs updating based on idea of using PARTS. Updates are to both the Web Component and external CSS

### Web component HTML
```html
<a tabindex="-1" id="lrnsys-button-link" part="lrnsys-button-link" ?disabled="${this.disabled}">
        <button
          id="button"
          title="${this.alt}"
          class="${this.buttonClass} ${this.color} ${this.textColor}"
	  part="lrnsys-button-button"
          ?disabled="${this.disabled}"
          @focus-changed="${this.focusToggle}"
        >
          <div class="inner ${this.innerClass}">
            <slot name="prefix"></slot>
            <simple-icon
              icon="${this.icon}"
              id="icon"
              ?dark="${this.dark}"
              accent-color="grey"
              contrast="4"
              class="${this.iconClass}"
              ?hidden="${!this.icon}"
			  part="lrnsys-button-icon"
            ></simple-icon>
            <span class="label" part="lrnsys-button-label" ?hidden="${!this.label}"> ${this.label} </span>
            <slot></slot>
          </div>
        </button>
      </a>
      <simple-tooltip part="lrnsys-button-tooltip"
        for="lrnsys-button-link"
        animation-delay="0"
        ?hidden="${!this.alt}"
        >${this.alt}</simple-tooltip
      >
```
### Web Component CSS
```css
/* set hand cursor for mouse over */
button {
cursor: pointer;
}
```

#### r-header
```css
/* change active menu item text color in r-header to white */ 
.r-header lrnsys-button.active span::part(lrnsys-button-label) {
color: white
}

/* change active menu item background color in r-header to dark green */
.r-header lrnsys-button.active button::part(lrnsys-button-button) {
background-color: #1f9289;
}

/* change menu item hover background color in r-header to dark green */
.r-header button.pink.darken-4::part(lrnsys-button-button) {
background-color: #1f9289;
}
```
#### etb-network-nav
```css
/* change menu item hover background color in etb-network-nav to dark green */
.etb-network-nav button.blue.darken-4::part(lrnsys-button-button) {
background-color: #1d8279;
}
```
#### etb-course-nav
```css
/* change menu item hover background color in etb-course-nav to slightly transparent */
.etb-course-nav button.pink.darken-4::part(lrnsys-button-button) {
background-color: rgba(0, 0, 0, 0.1) !important;
}

/* change menu item background color in etb-course-nav to transparent*/
etb-course-nav button.black::part(lrnsys-button-button)  {
background-color: rgba(0, 0, 0, 0);
}
```

**Comment by rickhumphries** [comment]
Based on back channel conversation, we should try to update the html in the shadow root to support parts - https://developer.mozilla.org/en-US/docs/Web/CSS/::part

Example would be to update this line:
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/lrnsys-button/lrnsys-button.js#L152
`<span class="label" part="lrnsys-button-label" ?hidden="${!this.label}"> ${this.label} </span>`

Then we could target it using selectors outside the shadow root with things like `lrnsys-button.active::part(label) {}` 

@JackWillDavis FYI

**Comment by rickhumphries** [comment]
This has worked. External CSS actually needs to look like this

```css
/* change active menu item text color in r-header to white */ 
.r-header lrnsys-button.active::part(lrnsys-button-label) {
color: white;
}

/* change active menu item background color in r-header to dark green */
.r-header lrnsys-button.active::part(lrnsys-button-button) {
background-color: #1f9289;
}

/* change menu item hover background color in r-header to dark green */
.r-header lrnsys-button[hover-class~="pink"][hover-class~="darken-4"]::part(lrnsys-button-button):hover {
background-color: #1f9289;
}

/* change menu item hover background color in etb-network-nav to dark green */
#etb-network-nav lrnsys-button[hover-class~="blue"][hover-class~="darken-4"]::part(lrnsys-button-button):hover {
background-color: #1d8279;
}

/* change menu item hover background color in etb-course-nav to slightly transparent */
#etb-course-nav lrnsys-button[hover-class~="pink"][hover-class~="darken-4"]::part(lrnsys-button-button):hover {
background-color: rgba(0, 0, 0, 0.1);
}

/* change menu item background color in etb-course-nav to transparent*/
#etb-course-nav lrnsys-button[button-class*="black"]::part(lrnsys-button-button)  {
background-color: rgba(0, 0, 0, 0);
}
```
