### ISSUE TITLE
simple-icon

### ISSUE THREAD

**Issue by rickhumphries** [buttercupstraining/lrnwebcomponents#7]
Need to get a part onto the svg element and use `filter` to target the svg icon. Something like...

```css
svg {
filter: var(--lrnsys-drawer-svg-icon-color, invert(27%) sepia(51%) saturate(2878%) hue-rotate(346deg) brightness(104%) contrast(97%));
}
```
_Originally posted by @rickhumphries in https://github.com/buttercupstraining/lrnwebcomponents/issues/1#issuecomment-766828557_
